// Partial class extension — enriches the Reqnroll-generated test fixture with
// Allure metadata and enables retry on failure.
// Do NOT modify WillscotHomepage.feature.cs (auto-generated by Reqnroll).
using Allure.NUnit;
using Allure.NUnit.Attributes;
using NUnit.Framework;
using WillscotAutomation.Support;

namespace WillscotAutomation.Features;

[AllureNUnit]
[AllureEpic("WillScot Website Quality")]
[AllureFeature("Homepage Validation")]
[AllureSuite("WillScot Homepage")]
[AllureOwner("WillScot QA Team")]
[AllureTag("willscot", "homepage", "playwright", "regression")]
[RetryOnFailure(1)]   // Retry each failed test 1 more time (2 total attempts).
                      // Each retry triggers a fresh BeforeScenario → new browser context.
public partial class WillScotHomepageValidationFeature
{
}
