// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WillscotAutomation.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("WillScot Homepage Validation")]
    public partial class WillScotHomepageValidationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "WillScot Homepage Validation", ("    As a user visiting the WillScot website\r\n    I want to verify the homepage lo" +
                "ads and displays all critical elements correctly\r\n    So that I can be confident" +
                " the site is fully functional"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "WillscotHomepage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
    #line hidden
#line 7
        await testRunner.GivenAsync("I am on the WillScot homepage", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-001 Verify homepage loads within 4 seconds")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("TC001")]
        public async System.Threading.Tasks.Task TC_001VerifyHomepageLoadsWithin4Seconds()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "TC001"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-001 Verify homepage loads within 4 seconds", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 14
        await testRunner.ThenAsync("the page should have loaded within 4 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-002 Verify hero banner displays correct headline")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("TC002")]
        public async System.Threading.Tasks.Task TC_002VerifyHeroBannerDisplaysCorrectHeadline()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "TC002"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-002 Verify hero banner displays correct headline", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 21
        await testRunner.ThenAsync("the hero banner should display the headline \"Every Link in the Chain\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-003 Verify Learn More CTA button is visible and clickable")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("TC003")]
        public async System.Threading.Tasks.Task TC_003VerifyLearnMoreCTAButtonIsVisibleAndClickable()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "regression",
                    "TC003"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-003 Verify Learn More CTA button is visible and clickable", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 28
        await testRunner.ThenAsync("the \"Learn more\" CTA button should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
        await testRunner.AndAsync("the \"Learn more\" CTA button should be enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-004 Verify no broken images console errors or JavaScript exceptions")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("quality")]
        [NUnit.Framework.CategoryAttribute("TC004")]
        public async System.Threading.Tasks.Task TC_004VerifyNoBrokenImagesConsoleErrorsOrJavaScriptExceptions()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "quality",
                    "TC004"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-004 Verify no broken images console errors or JavaScript exceptions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 36
        await testRunner.ThenAsync("there should be no broken images on the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
        await testRunner.AndAsync("there should be no browser console errors", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
        await testRunner.AndAsync("there should be no uncaught JavaScript exceptions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-005 Verify top-level navigation items are visible")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("navigation")]
        [NUnit.Framework.CategoryAttribute("TC005")]
        public async System.Threading.Tasks.Task TC_005VerifyTop_LevelNavigationItemsAreVisible()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "regression",
                    "navigation",
                    "TC005"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-005 Verify top-level navigation items are visible", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "NavItem"});
                table1.AddRow(new string[] {
                            "Products"});
                table1.AddRow(new string[] {
                            "Storage Containers"});
                table1.AddRow(new string[] {
                            "Office Trailers"});
                table1.AddRow(new string[] {
                            "Browse by Use"});
                table1.AddRow(new string[] {
                            "Solutions"});
                table1.AddRow(new string[] {
                            "About Us"});
                table1.AddRow(new string[] {
                            "Locations"});
                table1.AddRow(new string[] {
                            "Office Trailers for Sale"});
#line 45
        await testRunner.ThenAsync("the following navigation items should be visible", ((string)(null)), table1, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-006 Verify clicking Locations navigates to locations page")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("navigation")]
        [NUnit.Framework.CategoryAttribute("TC006")]
        public async System.Threading.Tasks.Task TC_006VerifyClickingLocationsNavigatesToLocationsPage()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "navigation",
                    "TC006"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-006 Verify clicking Locations navigates to locations page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 61
        await testRunner.WhenAsync("I click the \"Locations\" navigation item", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
        await testRunner.ThenAsync("the URL should contain \"/en/locations\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-007 Verify clicking Office Trailers for Sale navigates to sales showroom")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("navigation")]
        [NUnit.Framework.CategoryAttribute("TC007")]
        public async System.Threading.Tasks.Task TC_007VerifyClickingOfficeTrailersForSaleNavigatesToSalesShowroom()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "navigation",
                    "TC007"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-007 Verify clicking Office Trailers for Sale navigates to sales showroom", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 69
        await testRunner.WhenAsync("I click the \"Office Trailers for Sale\" navigation item", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
        await testRunner.ThenAsync("the URL should contain \"/en/sales-showroom\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-008 Verify page title contains WillScot branding")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("quality")]
        [NUnit.Framework.CategoryAttribute("TC008")]
        public async System.Threading.Tasks.Task TC_008VerifyPageTitleContainsWillScotBranding()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "regression",
                    "quality",
                    "TC008"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-008 Verify page title contains WillScot branding", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 77
        await testRunner.ThenAsync("the page title should contain \"WillScot\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-009 Verify clicking About Us navigates to about page")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("navigation")]
        [NUnit.Framework.CategoryAttribute("TC009")]
        public async System.Threading.Tasks.Task TC_009VerifyClickingAboutUsNavigatesToAboutPage()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "navigation",
                    "TC009"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-009 Verify clicking About Us navigates to about page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 84
        await testRunner.WhenAsync("I click the \"About Us\" navigation item", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
        await testRunner.ThenAsync("the URL should contain \"/en/about\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-010 Verify Request a Quote button is visible in header")]
        [NUnit.Framework.CategoryAttribute("smoke")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("TC010")]
        public async System.Threading.Tasks.Task TC_010VerifyRequestAQuoteButtonIsVisibleInHeader()
        {
            string[] tagsOfScenario = new string[] {
                    "smoke",
                    "regression",
                    "TC010"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-010 Verify Request a Quote button is visible in header", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 92
        await testRunner.ThenAsync("the \"Request a Quote\" button should be visible in the header", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-011 Verify clicking Request a Quote opens request quote page in same tab")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("TC011")]
        public async System.Threading.Tasks.Task TC_011VerifyClickingRequestAQuoteOpensRequestQuotePageInSameTab()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "regression",
                    "TC011"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-011 Verify clicking Request a Quote opens request quote page in same tab", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 99
        await testRunner.WhenAsync("I click the \"Request a Quote\" button in the header", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
        await testRunner.ThenAsync("the URL should contain \"/en/request-quote\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-012 Verify Request Support button navigates to request service page")]
        [NUnit.Framework.IgnoreAttribute("Ignored scenario")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("TC012")]
        public async System.Threading.Tasks.Task TC_012VerifyRequestSupportButtonNavigatesToRequestServicePage()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore",
                    "regression",
                    "TC012"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-012 Verify Request Support button navigates to request service page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 107
        await testRunner.WhenAsync("I click the \"Request Support\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
        await testRunner.ThenAsync("the URL should contain \"/en/request-service\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-013 Verify Storage Containers product card displays with image and label")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("products")]
        [NUnit.Framework.CategoryAttribute("TC013")]
        public async System.Threading.Tasks.Task TC_013VerifyStorageContainersProductCardDisplaysWithImageAndLabel()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "products",
                    "TC013"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-013 Verify Storage Containers product card displays with image and label", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 114
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 115
        await testRunner.ThenAsync("the Storage Containers product card should display with a visible image", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
        await testRunner.AndAsync("the Storage Containers product card label should read \"Storage Containers\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-014 Verify clicking Storage Containers card navigates correctly")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("products")]
        [NUnit.Framework.CategoryAttribute("TC014")]
        public async System.Threading.Tasks.Task TC_014VerifyClickingStorageContainersCardNavigatesCorrectly()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "products",
                    "TC014"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-014 Verify clicking Storage Containers card navigates correctly", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 122
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 123
        await testRunner.WhenAsync("I click the Storage Containers product card", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
        await testRunner.ThenAsync("the URL should contain \"/en/store-secure/storage-containers\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-015 Verify product images load without distortion or broken src")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("products")]
        [NUnit.Framework.CategoryAttribute("TC015")]
        public async System.Threading.Tasks.Task TC_015VerifyProductImagesLoadWithoutDistortionOrBrokenSrc()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "products",
                    "TC015"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-015 Verify product images load without distortion or broken src", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 130
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 131
        await testRunner.ThenAsync("all product images should return HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
        await testRunner.AndAsync("all product images should be visible on the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-016 Verify all product links return HTTP 200")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("products")]
        [NUnit.Framework.CategoryAttribute("TC016")]
        public async System.Threading.Tasks.Task TC_016VerifyAllProductLinksReturnHTTP200()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "products",
                    "TC016"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-016 Verify all product links return HTTP 200", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 138
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 139
        await testRunner.ThenAsync("all product links should return HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC-017 Verify industry solution tabs are displayed with correct names")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("industry")]
        [NUnit.Framework.CategoryAttribute("TC017")]
        public async System.Threading.Tasks.Task TC_017VerifyIndustrySolutionTabsAreDisplayedWithCorrectNames()
        {
            string[] tagsOfScenario = new string[] {
                    "regression",
                    "industry",
                    "TC017"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC-017 Verify industry solution tabs are displayed with correct names", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 145
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "TabName"});
                table2.AddRow(new string[] {
                            "Construction & Builders"});
                table2.AddRow(new string[] {
                            "Education & Government"});
                table2.AddRow(new string[] {
                            "Energy & Industrial"});
                table2.AddRow(new string[] {
                            "Retail & Distribution"});
                table2.AddRow(new string[] {
                            "Manufacturing"});
                table2.AddRow(new string[] {
                            "Healthcare & Entertainment"});
#line 146
        await testRunner.ThenAsync("the following industry solution tabs should be displayed", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
